//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTinTuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuDe
    {
        public string IDCD { get; set; }
        public string TenChuDe { get; set; }
    }
}
